name: Update gists
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-productive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update productive-box
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.BOX_PRODUCTIVE }}
          TIMEZONE: Asia/Seoul

  update-waka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update waka-box
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.BOX_WAKATIME }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
