name: Update Waka README
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  waka-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          # SHOW_EDITORS: "True"
          # SHOW_TIMEZONE: "True"
          # SHOW_COMMIT: "True"
          # SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          # SHOW_LANGUAGE_PER_REPO: "True"
          # SHOW_LOC_CHART: "True"
          # SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          # LOCALE: "en"
          # COMMIT_BY_ME: "False"
          # IGNORED_REPOS: ""
          # COMMIT_MESSAGE: "Updated with Dev Metrics"
          # SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y-%m-%dT%H:%M:%S"
          # SHOW_TOTAL_CODE_TIME: "True"
          # SYMBOL_VERSION: "1"
